/* © 2025 goodwordguide.com. All Rights Reserved. */
function ta(E){function r(H){return E.next(H)}function U(H){return E.throw(H)}return new Promise(function(H,u){function V(Q){Q.done?H(Q.value):Promise.resolve(Q.value).then(r,U).then(V,u)}V(E.next())})}
(()=>{function E(g,h){ba?console.error(g):g?v.O("REPORT_ERROR",{msg:g.message,stack:g.stack,url:h,lineNo:g.lineNumber,columNo:g.columnNumber,location:""}):console.log("Error in "+arguments.callee.caller)}const r=this,U=JSON.stringify,H=JSON.parse,u=r.chrome||this.browser,V=JSON.stringify,Q=JSON.parse,ia=r.Array,ja=r.String,ua=r.indexedDB||r.mozIndexedDB||r.webkitIndexedDB||r.msIndexedDB;void 0;r.Lock=(()=>{function g(){u.runtime.onMessageExternal.addListener((b,a)=>{const c=a.tab.windowId,k=URL.parse(a.url).searchParams;
B.j.g(y.l).then(p=>{p&&p.id===c&&a.origin==="https://"+this.domain&&"AUTHTICK_AUTH_CALLBACK"===b.action&&q.call(this,k.get("code"),k.get("state"))});d(c)})}function h(b){u.windows.remove(b).catch(()=>{})}function d(b){B.j.g(y.l).then(a=>{a&&a.id===b&&(h(a.id),B.j.F(y.l))})}function l(){var b=this.domain;const a="https://"+b;b="https://"+b+"/api";return{ea:a+"/authorize",fa:a+"/authorize",Y:b+"/signout",va:b+"/token",Ma:b+"/userinfo"}}function q(b,a){const c=this;f(a||w("state")).then(k=>K(k.codeChallenge).then(p=>
{p={code:b||w("code"),grant_type:"authorization_code",code_verifier:p};ka.call(c,p,k.state)}))}function e(b,a,c){a=Object.assign({},this.options,a);var k=Object.keys(R),p=Object.values(R).indexOf(b);k=k[p];p=n(m(32,64));var x=this.T,z=a.responseType||"code",A=a.redirectURI,L=a.scope,va=a.state;const la=n(m(16,24));B.j.Set("lock_state."+la,btoa(JSON.stringify({codeChallenge:p,state:va})));a={client_id:x,response_type:z,redirect_uri:A,scope:L,state:la,connections:a.connections,code_challenge:p,code_challenge_method:y.ha,
mode:c};if(k){b=this.S[k]+"?";c=[];a=Object.assign({},a);for(let ca in a)a[ca]&&(k=encodeURIComponent(a[ca]),c.push(`${ca}=${k}`));return b+c.join("&")}throw Error(`Invalid action "${b}".`);}function f(b){return B.j.g("lock_state."+b).then(a=>{a=a?atob(a):"null";B.j.F("lock_state."+b);return JSON.parse(a)})}function m(b,a){b=Math.ceil(b);a=Math.floor(a);return Math.floor(Math.random()*(a-b)+b)}function n(b){let a="",c=0;for(;c<b;)a+="ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789".charAt(Math.floor(62*
Math.random())),c+=1;return a}function t(b,a){var c;let k;const p=a.height||(I.I>(null==r?void 0:null==(c=r.screen)?void 0:c.availHeight)?null==r?void 0:null==(k=r.screen)?void 0:k.availHeight:I.I);let x,z;c=a.width||(I.J>(null==r?void 0:null==(x=r.screen)?void 0:x.availWidth)?null==r?void 0:null==(z=r.screen)?void 0:z.availWidth:I.J);b=e.call(this,b,a,"iframe");if(!b)return!1;const A=document.createElement("div");A.style.backgroundColor="#fff";A.style.display="none";A.style.height=`${p}px`;A.style.lineHeight=
`${p}px`;A.style.opacity=.66;A.style.textAlign="center";A.style.width=`${c}px`;A.textContent="Loading...";a=document.createElement("iframe");a.allow="fullscreen";a.setAttribute("allowFullScreen","");a.frameBorder="0";a.referrerPolicy="origin";a.scrolling="auto";a.src=b;a.style.height=`${p}px`;a.style.width=`${c}px`;r.setTimeout(()=>{A.style.display=""},125);return{s:a,D:A}}function w(b){let a=r.location.search.substring(1).split("&"),c=null;for(let k=0;k<a.length;k++){let p=a[k].split("=");if(p[0]===
b){c=p[1];break}}return c}function C(b){let a=r.location;b=URL.parse(b);return(null==a?void 0:a.protocol)===(null==b?void 0:b.protocol)&&(null==a?void 0:a.host)===(null==b?void 0:b.host)&&(null==a?void 0:a.port)===(null==b?void 0:b.port)&&(null==a?void 0:a.pathname)===(null==b?void 0:b.pathname)}function K(b){return ta(function*(){var a=(new TextEncoder).encode(b);a=yield crypto.subtle.digest("SHA-256",a);a=ia.from(new Uint8Array(a));return btoa(ja.fromCharCode(...a)).replace(/\+/g,"-").replace(/\//g,
"_").replace(/=+$/,"")}())}function F(b){b=b.split(".")[1].replace(/-/g,"+").replace(/_/g,"/");return JSON.parse(atob(b))}function G(b){return b?F(b).exp>Date.now()/1E3:!1}function ka(b,a){return ma(this.S.va+`?client_id=${this.T}&redirect_uri=${this.options.redirectURI}`,b).then(c=>{G(c[y.K])&&G(c[y.M])?this.triggerEvent("signInSuccess",{tokens:c,state:a}):this.triggerEvent("signInFailure",{state:a})}).catch(c=>c)}function ma(b,a){const c={method:"GET",headers:{"Content-Type":"application/json"}};
if(a){let k=new FormData;for(let p in a)k.append(p,a[p]);c.body=(new URLSearchParams(k)).toString();c.method="POST";c.headers["Content-Type"]="application/x-www-form-urlencoded"}return new Promise((k,p)=>{fetch(b,c).then(x=>{if(199<x.status&&300>x.status)return x.text().then(z=>{if(null==z?0:z.length)try{var A=JSON.parse(z);k(A)}catch(L){p(L)}else k()});p(Error(x.statusText))}).catch(x=>{p(x)})})}function wa(){return new Promise(b=>{O?u.system.display.getInfo(a=>{b({availHeight:a[0].workArea.height,
availWidth:a[0].workArea.width,height:a[0].bounds.height,width:a[0].bounds.width})}):b(r.screen)})}function xa(b,a){return new Promise(c=>{if(O)u.windows.create({focused:!0,height:a.height,left:a.left,top:a.top,type:"popup",url:b,width:a.width},k=>{c({id:k.id,url:k.url})});else{const k=r.open(b,"_blank",`name=${y.$},width=${a.width}px,height=${a.height}px,top=${a.top}px,left=${a.left}px,toolbar=0,menubar=0,location=0,resizable,scrollbars,status`);c({id:y.$,url:b,window:k})}})}function na(b){return new Promise((a,
c)=>{if(O)u.windows.update(b.id,{drawAttention:!0,focused:!0}).then(a).catch(c);else try{b.focus(),a()}catch(k){c(k)}})}function da(b,a){wa().then(c=>{const k=a.height||(I.I>(null==c?void 0:c.availHeight)?null==c?void 0:c.availHeight:I.I),p=a.width||(I.J>(null==c?void 0:c.width)?null==c?void 0:c.width:I.J);let x=a.left||Math.ceil(((null==c?NaN:c.width)-p)/2);c=a.top||Math.ceil(((null==c?NaN:c.availHeight)-k)/2);const z=e.call(this,b,a);if(!z)return!1;const A={height:k,left:0>x?0:x,top:0>c?0:c,width:p};
xa(z,A).then(L=>{na(L);B.j.Set(y.l,{id:L.id,url:L.url,La:A})})})}function ya(b,a){B.j.g(y.l).then(c=>{c?na(c).then(k=>{k||da.call(this,b,a)}).catch(()=>{da.call(this,b,a)}):da.call(this,b,a)})}const R={ea:"signIn",Y:"signOut",fa:"signUp"},za=["","complete","failure","success"],M={frame:"frame",h:"popup",ta:"popupWindow",redirect:"redirect",ua:"tab"},I={I:673,J:393},y={ha:"S256",R:"LOCK_TOKEN",Ca:"LOCK_STATE",l:"LOCK_AUTH_WINDOW",$:"LOCK_AUTH_WINDOW",m:"refresh_token",K:"access_token",M:"identity_token",
ja:"expires_at"},O=null==u?void 0:u.storage;class W{constructor(b,a,c,k={}){k.redirectURI=c||k.redirectURI;this.domain=a;this.T=b;this.options=k;this.U={};this.C={};this.W=this.V=this.B=this.o=this.A=this.X=null;this.onSignInSuccess(p=>{p=p.tokens;B.N.Set(y.R,p).catch(x=>{console.error(x)});this.X=p[y.m];this.A=p[y.K];this.o=p[y.M];this.B=F(this.A);this.W=F(this.o);this.V=new Date(this.B[y.ja])});this.onSignOutSuccess(()=>{B.N.F(y.R);this.V=this.W=this.B=this.o=this.A=this.X=null});this.S=l.call(this,
0);g.call(this);C(this.options.redirectURI)&&w("code")?q.call(this):B.N.g(y.R).then(p=>{(null==p?0:p[y.m])&&G(p[y.K])&&G(p[y.M])?this.triggerEvent("signInSuccess",{tokens:p}):(null==p?0:p[y.m])&&ka.call(this,{grant_type:y.m,[y.m]:p[y.m]})})}getSessionExpiry(){return this.V}getAccessToken(){return new Promise(b=>{b()})}getIdToken(){return this.o}getAccessTokenClaim(b){return this.B[b]}getIdTokenClaim(b){return this.W[b]}getUserID(){return r.parseInt(this.B.sub.split("|")[1],10)}isSignedIn(){return this.A&&
this.o&&G(this.A)&&G(this.o)}off(b,a){0<a&&((this.C[b]=this.C[b]=[])[a-1]=null);return this}on(b,a){if(b in this.U)a.call(this,this.U[b]);else return(this.C[b]=this.C[b]||[]).push(a)}repositionPopup(){if(this.h){const c=this.h.s,k=this.h.D;var b=this.h.options,a=r.parseInt(c.style.width,10);const p=r.parseInt(c.style.height,10);a=b.left||Math.ceil((r.innerWidth-a)/2);b=b.top||Math.ceil((r.innerHeight-p)/2);a=0>a?0:a;b=0>b?0:b;c.style.left=`${a}px`;c.style.top=`${b}px`;k.style.left=`${a}px`;k.style.top=
`${b}px`}}closePopup(){this.h&&(this.h.s.parentNode.removeChild(this.h.s),this.h.da.parentNode.removeChild(this.h.da),this.h=null)}signOut(b){const a=ma(this.S.Y,{client_id:this.T,token:this.X}).then(c=>{this.triggerEvent("signOutSuccess");return c}).catch(c=>{this.triggerEvent("signOutFailure");return c});b&&a.then(b);return a}triggerEvent(b,a){this.U[b]=a;(this.C[b]||[]).forEach(c=>{c.call(this,a)})}}const J={ga:function(b,a,c){let k=null;switch(a){case M.frame:k=J.wa;break;case M.h:k=J.Oa;break;
case M.ta:k=J.xa;break;case M.redirect:k=J.ya;break;case M.ua:k=J.za;break;case M.window:k=J.Pa}if(k)return k.call(this,b,c);throw Error(`Invalid ${({ea:"sign in",fa:"sign up"})[b]} method "${a}".`);},wa:function(b,a={}){let c=a.target;"string"===typeof c&&(c=document.querySelectorAll(c)[0]);c&&(b=t.call(this,b,a),"string"===typeof c&&(c=document.querySelectorAll(c)),c.appendChild(b.s))},Na:function(b,a={}){var c=t.call(this,b,a);b=c.s;const k=c.D;b.style.position="absolute";b.style.zIndex=2147483641;
k.style.position="absolute";k.style.zIndex=2147483642;c=document.createElement("div");c.style.backgroundColor="#000";c.style.position="absolute";c.style.height="100vh";c.style.left=0;c.style.opacity="0.33";c.style.top=0;c.style.width="100vw";c.style.zIndex=2147483640;this.h={options:a,s:b,da:c,D:k};a=this.repositionPopup;b.addEventListener("load",()=>{this.h.D.parentNode.removeChild(k);this.h.D=null});r.addEventListener("resize",a.bind(this));r.addEventListener("blur",a.bind(this));c.addEventListener("click",
this.closePopup.bind(this));document.body.appendChild(c);document.body.appendChild(b);document.body.appendChild(k)},xa:function(b,a={}){ya.call(this,b,a);return this},ya:function(b,a={}){b=e.call(this,b,a);if(!b)return!1;r.location=b;return this},za:function(b,a={}){b=e.call(this,b,a);if(!b)return!1;r.open(b);return this}};Object.values(R).forEach(b=>{za.forEach(a=>{W.prototype["on"+(b.charAt(0).toUpperCase()+b.slice(1))+(a.charAt(0).toUpperCase()+a.slice(1))]=function(c){return this.on(b+(a.charAt(0).toUpperCase()+
a.slice(1)),c)}});R[b]!==R.Y&&(W.prototype[b+"With"]=function(a,c){J.ga.call(this,b,a,c)},Object.values(M).forEach(a=>{W.prototype[b+"With"+(a.charAt(0).toUpperCase()+a.slice(1))]=function(c){return J.ga.call(this,b,a,c)}}))});u.windows.onRemoved.addListener(b=>{B.j.g(y.l).then(a=>{a&&a.id===b&&d(a.id)})});const ea=(b,a)=>b?{g:c=>new Promise((k,p)=>a.get([c]).then(x=>{try{var z=x[c];z&&(z=JSON.parse(z));k(z)}catch(A){p(A)}}).catch(x=>{p(x)})),Set:(c,k)=>new Promise((p,x)=>{try{k=JSON.stringify(k)}catch(z){x(z)}return a.set({[c]:k}).then(()=>
{p()}).catch(z=>{x(z)})}),F:c=>a.remove([c])}:{g:function(c){return new Promise((k,p)=>{try{var x=a.getItem(c);x&&(x=JSON.parse(x));k(x)}catch(z){p(z)}})},Set:function(c,k){return new Promise((p,x)=>{try{a.setItem(c,JSON.stringify(k)),p()}catch(z){x(z)}})},F:function(c){return new Promise(k=>{a.removeItem(c);k()})}},S=null==u?void 0:u.storage,Aa=(null==S?void 0:S.session)||(null==r?void 0:r.sessionStorage),B={N:ea(O,(null==S?void 0:S.local)||(null==r?void 0:r.localStorage)),j:ea(O,Aa)};O&&(B.Fa=ea(!0,
S.sync));return function(b,a,c,k){return new W(b,a,c,k)}})();const ba="nkhbjlenfobcenmkodlfnjncjclhfain"===u.runtime.id,Ba=u.runtime.getURL("/").replace(/\/$/,""),Ca=u.runtime.getManifest().version,oa=ba?".dev":"",Da=[`https://apis${oa}.goodwordguide.com`,`https://apis${oa}.goodwordguide.com`],pa={doubleClickEnabled:!0,doubleClickKey:"",fontSize:11,longClickEnabled:!0,selectionEnabled:!1,selectionKey:"",wordHistoryEnabled:!0},qa=(g,h)=>{h=h||"";fetch("https://clouderrorreporting.googleapis.com/v1beta1/projects/iwsn-a/events:report?key=AIzaSyCG_lia9Ayyt5PC5s71n-8j6Ky6WBs5zt8",
{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({serviceContext:{service:"Dictionary Bubble",version:Ca},context:{httpRequest:{userAgent:navigator.userAgent,url:h||(g&&g.location?g.location.href:g.url)},sourceReferences:[{repository:"https://github.com/GoodWordGuide/dictionary-bubble",revisionId:""}]},message:"string"===typeof g?`${g}: ${h}\n\tat ${"https://github.com/GoodWordGuide/dictionary-bubble"}:1:1`:g.stack.toString()})}).catch(d=>{console.error("CANNOT_SEND_ERROR_REPORT",
d)})};(()=>{const g=r.onerror;r.onerror=h=>{E(h);g&&g(h)}})();const T={};(()=>{const g=["0","0","0","0","0"],h=g.length;T.Ja=d=>Q(V(d));T.sa=()=>{let d=h,l;for(;d;){d--;l=g[d].charCodeAt(0);if(57==l)return g[d]="A",g.join("");if(90==l)g[d]="0";else return g[d]=ja.fromCharCode(l+1),g.join("")}g.unshift("0");return g.join("")};T.Ka=()=>"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,d=>{const l=16*Math.random()|0;return("x"==d?l:l&3|8).toString(16)});T.Ha=(d,l,q,e)=>{q=Math.min(q/d,e/l);return{width:d*
q,height:l*q}}})();var fa;(()=>{function g(){this.G={}}const h={};fa=d=>d?h[d]=h[d]||new g(d):new g;g.prototype={ka:function(d,l){d=this.G[d];for(let q in d)d[q](l);return this},la:function(d,l){const q=T.sa();this.G[d]=this.G[d]||{};this.G[d][q]=l;return q}}})();var ra;(()=>{function g(h,d,l){l||"string"===typeof d||(l=d,d=void 0);d||(d="GET",l&&(d="POST"));this.H={method:d,body:void 0,headers:{}};this.url=h;(ia.isArray(l)||"object"===typeof l)&&this.Body(l)}g.prototype={Body:function(h){this.H=
JSON.stringify(h);this.ba("Content-Type","application/json");return this},ba:function(h,d){this.H.headers[h]=d;return this},O:function(){this.H.signal=AbortSignal.timeout(3E3);return new Promise((h,d)=>{fetch(this.url,this.H).then(l=>{l.text().then(q=>{var e=null;q.length&&(e=JSON.parse(q));h({ok:200<=l.status&&300>l.status,status:l.status,headers:l.headers,statusText:l.statusText.toUpperCase().replaceAll(" ","_"),data:e,error:null})})}).catch(l=>{d({ok:!1,status:500,headers:{},statusText:"NETWORK_ERROR",
data:null,error:l})})})},qa:function(h){this.ba("Authorization",`Bearer ${h}`);return this}};ra=(h,d,l)=>new g(h,d,l)})();var X;(()=>{const g={},h=RegExp("s","g");X=(d,l,q,e)=>{const f={};d=d.toUpperCase().replace(h,"_");g[d]=q;f[e?"periodInMinutes":"delayInMinutes"]=l;return u.alarms.create(d,f)};X.clear=d=>{d=d.toUpperCase().replace(h,"_");delete g[d];u.alarms.clear(d)};u.alarms&&u.alarms.onAlarm.addListener(d=>{d=d.name;g[d]&&g[d]()})})();var P,ha;(()=>{const g=h=>{const d=u.storage[h];return{g:l=>
new Promise((q,e)=>d.get([l]).then(f=>{q(f[l])}).catch(f=>{E(f);e(f)})),Set:(l,q)=>d.set({[l]:q}).catch(e=>{E(e)})}};P=g("local");ha=g("sync");g("session")})();const Ea=(()=>{function g(n,t,w){return new Promise((C,K)=>{if(d){let F=d.transaction([n],"readwrite").objectStore(n)[t](w);F.onerror=G=>{K(G);E(G)};F.onsuccess=()=>{C(F.result)}}else return m.ready.then(()=>g(n,t,w))})}function h(n){this.name=n;q.push(n)}let d,l=ua.open("KV_STORES",2),q=[];const e=new Promise((n,t)=>{l.onupgradeneeded=function(w){d=
w.target.result;q.forEach(C=>{d.objectStoreNames.contains(C)||(this.store=d.createObjectStore(C,{keyPath:"key"}))});n()};l.onsuccess=function(w){d=w.target.result;n()};l.oncomplete=function(w){d=w.target.result;n()};l.onerror=function(w){E(w);t(w)}}),f={};h.prototype.aa=function(){return g(this.name,"clear",null)};h.prototype.L=function(){return g(this.name,"count",null)};h.prototype.g=function(n){return g(this.name,"get",n).then(t=>t?t.value:void 0)};h.prototype.v=function(){return g(this.name,"getAll",
null)};h.prototype.Set=function(n,t){return g(this.name,"get",n).then(w=>{w=w||{key:n};w.value=t;return g(this.name,"put",w)})};const m=n=>f[n]=f[n]||new h(n);m.ready=e;return m})(),v={};(()=>{const g={},h=u.extension&&"function"===typeof u.extension.getBackgroundPage?u.extension.getBackgroundPage():null;let d=Object.is(h,r);const l=(e,f,m)=>({command:e,args:f||null,waiting:m?!0:!1}),q=(e,f,m)=>{if("backgroundPage"===e.target&&!d)return!1;const n=g[e.command]||[],t=n.length;if(t){for(let w=0;w<t;w++)n[w](e.args,
C=>{m(C)},f);!e.waiting&&m&&m(!0)}return!0};d&&(r.__MessageReceiver=q);v.ra=()=>{d=!0;r.__MessageReceiver=q};v.i=(e,f)=>{if((e=(e||"").trim())&&"function"===typeof f){var m=g[e]||[];m.push(f);g[e]=m}};v.Ba=(e,f)=>{e=(e||"").trim();if(!e||!f)return!1;f=f.split(":");e=g[e];const m=f[1]?r.parseInt(f[1],10):0;return e&&f[1]&&m&&e[m]?(e.splice(m-1,1),!0):!1};v.na=e=>{var f=void 0;var m="AUTH_ON_STATUS_CHANGE";if(!m)return!1;"function"===typeof e&&(f=e,e=null);try{u.runtime.sendMessage(l(m,e,f),f).catch(n=>
n)}catch(n){return!1}return!0};v.P=(e,f,m,n)=>{f=(f||"").trim();if(!e||!f)return!1;"function"===typeof m&&(n=m,m=null);try{return u.tabs.sendMessage(e,l(f,m,n),n).catch(t=>t)}catch(t){return!1}};v.Ea=(e,f,m)=>{e=(e||"").trim();if(!e)return!1;"function"===typeof f&&(m=f,f=null);q(l(e,f,m),{},m)};v.ca=(e,f,m)=>{if(e=(e||"").trim()){"function"===typeof f&&(m=f,f=null);try{u.tabs.query({},n=>{for(let t=0,w=n.length;t<w;t++)v.P(n[t].id,e,f,m)})}catch(n){}}};v.Da=(e,f,m)=>{e=(e||"").trim();if(!e)return!1;
"function"===typeof f&&(m=f,f=null);try{u.tabs.query({active:!0,currentWindow:!0},n=>{v.P(n[0].id,e,f,m).catch(t=>t)})}catch(n){return!1}return!0};v.ma=e=>{v.na(e)&&v.ca("AUTH_ON_STATUS_CHANGE",e)};v.O=(e,f,m)=>{e=(e||"").trim();if(!e)return!1;"function"===typeof f&&(m=f,f=null);try{if(d)r.__MessageReceiver(l(e,H(U(f)),m),{},n=>{n=H(U(n));m(n)});else{const n=l(e,f,m);n.target="backgroundPage";u.runtime.sendMessage(n,m).catch(t=>t)}}catch(n){return!1}return!0};u.runtime.onMessage.addListener(q);d&&
v.i("__ECHO_SERVICE__",(e,f,m)=>{v.P(m.tab.id,e.command,e.args,e.callback?n=>{f(n)}:null)})})();const Y={};(()=>{let g;Y.v=h=>{if(g)return h(g),!0;try{ha.g("appSettings").then(d=>{d?(g=d,h(d)):h(pa)})}catch(d){h(pa),E(d)}return!1};Y.oa=(h,d)=>{try{ha.Set("appSettings",h).then(()=>{g=h;d&&d(!0)})}catch(l){d&&d(!0),console.error(l)}}})();const N={};(()=>{const g=Ea("WORD_HISTORY");N.Aa=h=>{h=h.toLowerCase();g.g(h).then(d=>{d.count++;d.date=new Date;g.Set(h,d).catch(l=>{E(l)})}).catch(()=>{g.Set(h,{word:h,
count:1,date:new Date})});return!0};N.aa=()=>g.aa();N.L=h=>g.L().then(h);N.v=h=>g.v().then(h)})();const Z={};(()=>{Z.u=()=>(g,h)=>{const d=null==g?void 0:g.data;if(!d)return g;const l=d.data.searchResults||[];d.term=h;for(let q in l)h=l[q],"dictionary"===h.source&&Z.u.ia(h);return g};Z.u.ia=g=>{const h={},d={},l=g.order,q=l.length;for(let n=0;n<q;n++){let t=g.definitions[l[n]],w=t.length;for(let C=0;C<w;C++){var e=t[C].synonyms;let K=t[C].antonyms;if(e){var f=e.length;for(var m=0;m<f;m++){let F=e[m];
h[F]=h[F]||0;h[F]++}}if(K)for(e=K.length,f=0;f<e;f++)m=K[f],d[m]=d[m]||0,d[m]++}}g.synonyms=Object.keys(h);g.antonyms=Object.keys(d)}})();const aa={};(()=>{const g=(h,d)=>l=>new Promise((q,e)=>{Promise.all([P.g("API_SERVER_HOST"),D.getAccessToken()]).then(f=>{const m=f[1],n=`${f[0]}${`/api/v2/${h}/${l}`}`;ra(n).qa(m).O().then(t=>{if(d)try{t=d(t,l),q(t)}catch(w){qa(w,n)}}).catch(t=>{q(t);sa()})}).catch(f=>{e(f)})});aa.u=g("define",Z.u());aa.pa=g("suggestions")})();var sa=null;(()=>{function g(q,e){return new Promise(f=>
{const m=Date.now();fetch(q+e,{method:"HEAD",signal:AbortSignal.timeout(5E3)}).then(n=>{f({host:q,Z:200<=n.status||300>n.status,latency:Date.now()-m,error:null})}).catch(n=>{f({host:q,Z:!1,latency:Date.now()-m,error:n})})})}function h(q,e){var f=[];Da.forEach(m=>{f.push(g(m,q,e))});return Promise.all(f).then(m=>{m=m.filter(n=>n.Z).sort((n,t)=>n.latency-t.latency);m.length&&P.Set("API_SERVER_HOST",m[0].host);return m})}function d(){h("/-/ping","ERR_API_PING").then(q=>{1<(null==q?void 0:q.length)&&
h("/-/ping","ERR_API_PING")})}function l(){P.g("LAST_API_PROBE_AT").then(q=>{12E4<Date.now()-(q||0)&&(P.Set("LAST_API_PROBE_AT",Date.now()),d())}).catch(()=>{})}X("SERVER_CONNECT",5,function(){P.g("API_SERVER_HOST").then(q=>{g(q,"/-/connect","ERR_API_CONNECT").then(e=>{e.Z||l()})}).catch(()=>{})},!0);X("SERVER_PING",120,d,!0);fa("GLOBAL_EVENTS").la("FIRST_TIME_INSTALLATION",d);sa=l})();console.Ga={id:1,name:"Webmaster",email:"webmaster@goodwordguide.com",subscription:{id:1,premium:!1,entitlements:{WIKIPEDIA_IMAGES:!1,
WIKIPEDIA_PRONUNCIATION:!1,WIKIPEDIA_CAPTION:!1,TERM_AUTOCOMPLETE:!1,TERM_SEARCH:!1,SEARCH_HISTORY:!1,WIKIPEDIA:!0,DICTIONARY:!0}}};const D=r.Lock("dictionary-bubble-extension-221.clientapps.authtick.com",`auth${ba?".dev":""}.goodwordguide.com`,Ba,{connections:["google-80"]});(()=>{const g=u.contextMenus,h=u.tabs;let d=!1;const l=()=>{v.ma(q())},q=()=>D.isSignedIn()?{name:D.getIdTokenClaim("name"),email:D.getIdTokenClaim("email"),picture:D.getIdTokenClaim("picture"),id:D.getUserID(),emailVerified:D.getIdTokenClaim("email_verified")}:
null;D.onSignInSuccess(l);D.onSignUpSuccess(l);D.onSignOutSuccess(l);u.runtime.onInstalled.addListener(e=>{"install"===e.reason&&(d=!0,u.runtime.openOptionsPage(),fa("GLOBAL_EVENTS").ka("FIRST_TIME_INSTALLATION"))});v.ra();v.i("AUTH_GET_USER",(e,f)=>{f(q())});v.i("AUTH_SIGN_IN",()=>{D.signInWithPopupWindow()});v.i("AUTH_SIGN_UP",()=>{D.signUpWithPopupWindow()});v.i("DEFINE",(e,f)=>{aa.u(e.term).then(f)});v.i("SUGGEST",(e,f)=>{aa.pa(e.term).then(f)});v.i("REPORT_ERROR",e=>{qa(e,null)});v.i("FIRST_RUN",
(e,f)=>{f(d)});v.i("USER_PREFERENCES_GET_ALL",(e,f)=>{Y.v(f)});v.i("USER_PREFERENCES_SET_ALL",(e,f)=>{Y.oa(e,()=>{f(!0);v.ca("USER_PREFERENCES_UPDATED",e,null)})});v.i("WORD_HISTORY_CLEAR",(e,f)=>{f(N.Ia())});v.i("WORD_HISTORY_COUNT",(e,f)=>{N.L(f)});v.i("WORD_HISTORY_GET_ALL",(e,f)=>{N.v(f)});u.omnibox.onInputEntered.addListener(e=>{const f="https://goodwordguide.com/define/"+e.replace(/\s+/g,"+");h.getSelected(null,m=>{h.update(m.id,{url:f})})});g.removeAll(()=>{g.create({id:"gwgd-search",title:"Search dictionary for \u201c%s\u201d",
contexts:["selection"]})});g.onClicked.addListener(e=>{"gwgd-search"==e.menuItemId&&h.create({url:"https://goodwordguide.com/define/"+e.selectionText.replace(/\s+/g,"+")});return!0})})()})();
//# sourceMappingURL=background.js.map