/* © 2025 goodwordguide.com. All Rights Reserved. */
(()=>{function S(h,v){V?console.error(h):h?A.C("REPORT_ERROR",{msg:h.message,stack:h.stack,url:v,lineNo:h.lineNumber,columNo:h.columnNumber,location:""}):console.log("Error in "+arguments.callee.caller)}const C=this,J=C.document,X=JSON.stringify,Y=JSON.parse,F=C.chrome||this.browser,ea=JSON.stringify,fa=JSON.parse,P=C.Array,ha=C.String,V="nkhbjlenfobcenmkodlfnjncjclhfain"===F.runtime.id;F.runtime.getURL("/").replace(/\/$/,"");F.runtime.getManifest();const ia={de:{DE:["Google Deutsch"]},en:{US:["Google US English"],
GB:["Google UK English Female","Google UK English Male"]},es:{US:["Google espa\u00f1ol de Estados Unidos"],ES:["Google espa\u00f1ol"]},fr:{FR:["Google fran\u00e7ais"]},hi:{IN:["Google \u0939\u093f\u0928\u094d\u0926\u0940"]},id:{ID:["Google Bahasa Indonesia"]},it:{IT:["Google italiano"]},ja:{JP:["Google \u65e5\u672c\u8a9e"]},ko:{KR:["Google \ud55c\uad6d\uc758"]},nl:{NL:["Google Nederlands"]},pl:{PL:["Google polski"]},pt:{BR:["Google portugu\u00eas do Brasil"]},ru:{RU:["Google \u0440\u0443\u0441\u0441\u043a\u0438\u0439"]},
zh:{CN:["Google \u666e\u901a\u8bdd\uff08\u4e2d\u56fd\u5927\u9646\uff09"],HK:["Google \u7ca4\u8a9e\uff08\u9999\u6e2f\uff09"],TW:["Google \u570b\u8a9e\uff08\u81fa\u7063\uff09"]}},A={};(()=>{const h={},v=F.extension&&"function"===typeof F.extension.getBackgroundPage?F.extension.getBackgroundPage():null;let m=Object.is(v,C);const t=(f,l,p)=>({command:f,args:l||null,waiting:p?!0:!1}),c=(f,l,p)=>{if("backgroundPage"===f.target&&!m)return!1;const r=h[f.command]||[],a=r.length;if(a){for(let e=0;e<a;e++)r[e](f.args,
k=>{p(k)},l);!f.waiting&&p&&p(!0)}return!0};m&&(C.__MessageReceiver=c);A.Ga=()=>{m=!0;C.__MessageReceiver=c};A.O=(f,l)=>{if((f=(f||"").trim())&&"function"===typeof l){var p=h[f]||[];p.push(l);h[f]=p}};A.Aa=(f,l)=>{f=(f||"").trim();if(!f||!l)return!1;l=l.split(":");f=h[f];const p=l[1]?C.parseInt(l[1],10):0;return f&&l[1]&&p&&f[p]?(f.splice(p-1,1),!0):!1};A.ca=(f,l,p)=>{f=(f||"").trim();if(!f)return!1;"function"===typeof l&&(p=l,l=null);try{F.runtime.sendMessage(t(f,l,p),p).catch(r=>r)}catch(r){return!1}return!0};
A.D=(f,l,p,r)=>{l=(l||"").trim();if(!f||!l)return!1;"function"===typeof p&&(r=p,p=null);try{return F.tabs.sendMessage(f,t(l,p,r),r).catch(a=>a)}catch(a){return!1}};A.Da=(f,l,p)=>{f=(f||"").trim();if(!f)return!1;"function"===typeof l&&(p=l,l=null);c(t(f,l,p),{},p)};A.da=(f,l,p)=>{f=(f||"").trim();if(!f)return!1;"function"===typeof l&&(p=l,l=null);try{return F.tabs.query({},r=>{for(let a=0,e=r.length;a<e;a++)A.D(r[a].id,f,l,p)}),!0}catch(r){return!1}};A.S=(f,l)=>{if(f=(f||"").trim()){if("function"===
typeof l){var p=l;l=null}try{F.tabs.query({active:!0,currentWindow:!0},r=>{A.D(r[0].id,f,l,p).catch(a=>a)})}catch(r){}}};A.Ca=(f,l,p)=>A.ca(f,l,p)&&A.da(f,l,p);A.C=(f,l,p)=>{if(f=(f||"").trim()){"function"===typeof l&&(p=l,l=null);try{if(m)C.__MessageReceiver(t(f,Y(X(l)),p),{},r=>{r=Y(X(r));p(r)});else{const r=t(f,l,p);r.target="backgroundPage";F.runtime.sendMessage(r,p).catch(a=>a)}}catch(r){}}};F.runtime.onMessage.addListener(c);m&&A.O("__ECHO_SERVICE__",(f,l,p)=>{A.D(p.tab.id,f.command,f.args,
f.callback?r=>{l(r)}:null)})})();(()=>{const h=C.onerror;C.onerror=v=>{S(v);h&&h(v)}})();const R={};(()=>{const h=["0","0","0","0","0"],v=h.length;R.fa=m=>fa(ea(m));R.pa=()=>{let m=v,t;for(;m;){m--;t=h[m].charCodeAt(0);if(57==t)return h[m]="A",h.join("");if(90==t)h[m]="0";else return h[m]=ha.fromCharCode(t+1),h.join("")}h.unshift("0");return h.join("")};R.Ia=()=>"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,m=>{const t=16*Math.random()|0;return("x"==m?t:t&3|8).toString(16)});R.Fa=(m,t,c,
f)=>{c=Math.min(c/m,f/t);return{width:m*c,height:t*c}}})();const ma=function(){function h(b){return Object.prototype.toString.call(b).slice(8,-1).toLowerCase()}function v(b=""){return"false null undefined 0 -0 NaN 0n -0n".split(" ").includes(b)}function m(b,d,g,q){if(!b||!d)return Error("You did not provide an element or event name.");d=new CustomEvent(d,{bubbles:!0,cancelable:!q,detail:g});return b.dispatchEvent(d)}function t(b,d){function g(x){for(let E in b)b.hasOwnProperty(E)&&(x[E]=t(b[E],d))}
function q(){let x={};g(x);return x}function y(){return b.map(function(x){return t(x,d)})}function w(){let x=new Map;for(let [E,Q]of b)x.set(E,t(Q,d));return x}function z(){let x=new Set;for(let E of b)x.add(t(E,d));return x}function G(){let x=b.bind(this);g(x);return x}function K(){return b.replace(/javascript:/gi,"").replace(/[^\w-_. ]/gi,function(x){return`&#${x.charCodeAt(0)};`})}let D=h(b);return"object"===D?q():"array"===D?y():"map"===D?w():"set"===D?z():"function"===D?G():"string"!==D||d?b:
K()}function c(b){b.H&&window.cancelAnimationFrame(b.H);b.H=window.requestAnimationFrame(function(){b.I()})}function f(b){return{get:function(d,g){return-1<["object","array"].indexOf(h(d[g]))?new Proxy(d[g],f(b)):d[g]},set:function(d,g,q){if(d[g]===q)return!0;d[g]=q;c(b);return!0}}}function l(b){let d=(new DOMParser).parseFromString(b,"text/html");d.head&&d.head.childNodes&&0<d.head.childNodes.length&&P.from(d.head.childNodes).reverse().forEach(function(g){d.body.insertBefore(g,d.body.firstChild)});
return d.body||document.createElement("body")}function p(b,d){d.forEach(function(g){if("class"===g.h)b.className=g.value;else if("style"===g.h)b.style.cssText=g.value;else{if(g.h in b)try{b[g.h]=g.value,b[g.h]||0===b[g.h]||(b[g.h]="value"===g.h?g.value:!0)}catch(q){}try{b.setAttribute(g.h,g.value)}catch(q){}}})}function r(b,d){d.forEach(function(g){if("class"===g.h)b.className="";else if("style"===g.h)b.style.cssText="";else{if(g.h in b)try{b[g.h]=""}catch(q){}try{b.removeAttribute(g.h)}catch(q){}}})}
function a(b,d){return{h:b,value:d}}function e(b,d){return 1!==b.nodeType?[]:P.from(b.attributes).map(function(g){if(!(d&&W.includes(g.name)&&ja.includes(b.tagName.toLowerCase()))){if(!d&&W.includes(g.name))return a(g.name,b[g.name]);if(!Z.includes(g.name)){if(d&&aa.includes(g.name)){let q=g.name.replace("reef-","");return T.includes(q)?a(q,v(g.value)?null:q):a(q,g.value)}return a(g.name,g.value)}}}).filter(function(g){return!!g})}function k(b,d){let g=e(b,!0),q=e(d);b=q.filter(function(w){let z=
g.find(function(G){return w.h===G.h});return void 0===z&&!W.includes(w.h)||z&&T.includes(z.h)&&null===z.value});let y=g.filter(function(w){if(T.includes(w.h)&&null===w.value)return!1;let z=q.find(function(G){return w.h===G.h});return void 0===z||z.value!==w.value});p(d,y);r(d,b)}function u(b){1===b.nodeType&&(P.from(b.attributes).forEach(function(d){if(aa.includes(d.name)||Z.includes(d.name)){var g=d.name.replace("reef-default-","").replace("reef-",""),q=T.includes(g);r(b,[a(d.name,d.value)]);q&&
v(d.value)||p(b,[q?a(g,g):a(g,d.value)])}}),b.childNodes&&P.from(b.childNodes).forEach(function(d){u(d)}))}function n(b){return 3===b.nodeType?"text":8===b.nodeType?"comment":b.tagName.toLowerCase()}function I(b){return b.childNodes&&0<b.childNodes.length?null:b.textContent}function M(b,d){return n(b)!==n(d)||b.id!==d.id||b.src!==b.src}function ka(b,d,g){return P.from(d).slice(g+1).find(function(q){return!M(b,q)})}function la(b,d){d=b.length-d.length;if(!(1>d))for(;0<d;d--)b[b.length-d].remove(b[b.length-
d])}function U(b,d,g=[]){let q=d.childNodes;b=b.childNodes;b.forEach(function(y,w){if(q[w]){if(M(y,q[w])){var z=ka(y,q,w);if(!z){u(y);q[w].before(y.cloneNode(!0));return}q[w].before(z)}k(y,q[w]);0<g.filter(function(G){return![3,8].includes(y.nodeType)&&y.matches(G)}).length||((z=I(y))&&z!==I(q[w])&&(q[w].textContent=z),0<q[w].childNodes.length&&1>y.childNodes.length?q[w].innerHTML="":1>q[w].childNodes.length&&0<y.childNodes.length?(z=document.createDocumentFragment(),U(y,z,g),q[w].appendChild(z)):
0<y.childNodes.length&&U(y,q[w],g))}else u(y),d.append(y.cloneNode(!0))});la(q,b)}function ba(b,d){b&&b.forEach(function(g){g.l.includes(d)?N(`"${d.u}" has attached nodes that it is also attached to, creating an infinite loop.`):"render"in g&&g.I()})}function O(b,d){if(b||d&&d.A)if(d&&(d.m||d.A)){var g=this,q=d.ya?d.store?null:d.data:d.data&&!d.store?new Proxy(d.data,f(g)):null,y=d.G?"array"===h(d.G)?d.G:[d.G]:[],{store:w,J:z,ya:G,Na:K}=d;g.H=null;Object.defineProperties(g,{u:{value:b},m:{value:d.m},
F:{value:d.F},A:{value:d.A},store:{value:w},l:{value:[]},methods:{value:d.methods||{}},Z:{value:d.Z||(()=>{})},data:{get:function(){return G?t(q,!0):q},set:function(D){if(w||G)return!0;q=new Proxy(D,f(g));c(g);return!0},configurable:!0},get:{value:function(D){if(w||!K)N("There are no getters for this component.");else{if(K[D]){var x=P.from(arguments);x[0]=q;return K[D].apply(g,x)}N("There is no getter with this name.")}},configurable:!0}});z&&"addComponent"in z&&z.Ja(g);w&&"attach"in w&&w.Y(g);y.length&&
y.forEach(function(D){"attach"in D&&D.Y(g)});m(document,"reef:initialized",g)}else N("You did not provide a template for this component.");else N("You did not provide an element to make into a component.")}let ca=V,N;N=V?b=>{ca&&console.warn(b)}:()=>{};let W=["checked","selected","value"],T=["checked","selected"],ja=["input","option","textarea"],aa=["reef-checked","reef-selected","reef-value"],Z=["reef-default-checked","reef-default-selected","reef-default-value"];O.prototype.I=function(){if(this.A)ba(this.l,
this);else if(this.m){var b="string"===h(this.u)?document.querySelector(this.u):this.u;if(b){var d=t((this.store?this.store.data:this.data)||{},this.F),g="function"===h(this.m)?this.m(d,this.methods,this.J&&this.J.current?this.J.current:b,b):this.m;if(["string","number"].includes(h(g))&&m(b,"reef:before-render",d)){var q=this.l.map(function(y){return y.u});U(l(g),b,q);m(b,"reef:render",d);m(b,"render",d);ba(this.l,this);b=b.querySelectorAll("*");for(let y=0,w=b.length;y<w;y++){d=b[y];g=d.getAttributeNames();
for(let z=0,G=g.length;z<G;z++)if(q=g[z],-1<q.indexOf("on:")){let K=q.substr(3).split("."),D=d.getAttribute(q);d["on"+K[0]]=x=>{-1!==K.indexOf("stop")&&(x.stopPropagation(),x.stopImmediatePropagation());-1!==K.indexOf("prevent")&&x.preventDefault();var E,Q,L=null==(E=D)?void 0:null==(Q=E.trim())?void 0:Q.match(/(.*?)\((.*)\)/);Q=D;E=[];L&&2<L.length&&L[2].trim()&&(E=JSON.parse("["+L[2].trim()+"]"));E.push(x);L&&L[1]&&(Q=L[1]);x=Q.split(".")[1];if(L=this.methods[x])return L.apply(this,E);x&&S(new C.Error(x+
" is not a valid method"))}}}}}else N("The DOM element to render your template into was not found.")}else N("No template was provided.")};O.prototype.Y=function(b){b="array"===h(b)?b:[b];for(let d of b)this.l.push(d);m(document,"reef:attached",{component:this,l:b})};O.prototype.detach=function(b){b="array"===h(b)?b:[b];for(let d of b){let g=this.l.indexOf(d);if(0>g)return;this.l.splice(g,1)}m(document,"reef:detached",{component:this,Ka:b})};O.use=function(b){b.$&&"function"===typeof b.$&&(b.$(O,{La:U}),
m(document,"reef:plugin-added",b))};O.debug=function(b){ca=b?!0:!1};O.clone=t;m(document,"reef:ready");return O}();var B;(()=>{function h(){}let v=!1,m=[];const t=!C.addEventListener&&C.attachEvent?(a,e,k)=>{a.attachEvent("on"+e,k)}:(a,e,k,u)=>{a.addEventListener(e,k,u)},c=a=>function(e,k){e?this.i(u=>{t(u,a,n=>{n.ma=n.preventDefault?n.preventDefault:()=>n.returnValue=!1;n.oa=n.stopPropagation?n.stopPropagation:()=>{n.cancelBubble=!0};n.na=n.stopImmediatePropagation?n.stopImmediatePropagation:()=>
{n.ra=!0};n.Ha=()=>{n.ma();n.oa();n.na()};if(!n.ra)return!1===e(n,u)?!1:!0},k)}):this.i(u=>{{let n;if(u[a])u[a]();else J.createEvent?(n=J.createEvent("HTMLEvents"),n.initEvent(a,!0,!0)):(n=J.createEventObject(),n.ta=a),n.Ma=a,J.createEvent?u.dispatchEvent(n):u.fireEvent("on"+n.ta,n)}});return this};h.prototype=[];h.prototype.constructor=h;h.prototype.ia=h.prototype.indexOf;h.prototype.j=h.prototype.push;h.prototype.i=function(a){for(let e=0,k=this.length;e<k&&!1!==a(this[e],e,this);e++);};c("abort");
c("beforeunload");c("blur");c("change");c("click");c("dblclick");c("error");h.prototype.ha=c("focus");c("focusin");c("focusout");c("gesturestart");c("gesturechange");c("input");c("keydown");c("keypress");c("keyup");c("load");c("orientationchange");c("message");c("mousedown");c("mouseenter");c("mouseleave");c("mousemove");c("mouseout");c("mouseover");c("mouseup");c("popstate");c("resize");c("scroll");c("select");c("selectionchange");c("submit");c("touchstart");c("touchmove");c("touchend");c("touchcancel");
c("unload");h.prototype.T=function(a){const e=B(a);this.i(k=>{e.i(u=>{k.appendChild(u)})})};h.prototype.ea=function(){return this[0]&&this[0].getAttribute?this[0].getAttribute("value"):""};h.prototype.fa=function(a){const e=B([]);this.i(k=>{e.j(k.cloneNode(a))});return e};h.prototype.ga=function(){const a=B([]);this.i(e=>{a.j.apply(a,e.childNodes)});return a};h.prototype.U=function(){this.i(a=>{for(;a.firstChild;)a.removeChild(a.firstChild)});return this};h.prototype.V=function(a){if("string"===typeof a){let e=
B(a,l(this[0]));return B(this.filter(k=>-1<e.ia(k)))}return"function"===typeof a?B(this.filter(a)):this};h.prototype.W=function(a){if(void 0===a)return this.ga().V(e=>1===e.nodeType);a instanceof h?(this.U(),this.T(a)):null!==a&&this.i(e=>{B(e).U().T(B(a))});return this};h.prototype.ka=function(a){const e=this;let k;if("function"===typeof a){k=a;var u=void 0}else k=n=>{const I=n.target;let M=B(I).la();M.j(I);M=M.V(a);if(M.length)return(void 0)(n,M[0])};B("click".replace(/\s+/g,"").split(",")).i(n=>
{c(n).call(e,k,u)})};h.prototype.la=function(){const a=B([]);this.i(e=>{const k=[];for(;e;)k.unshift(e),e=e.parentNode;a.j.apply(a,k)});return a};h.prototype.X=function(a){if(void 0===a){const e=[];this.i(k=>{e.push(k.value)});return 2>e.length?e.join():e}this.i(e=>{if("checkbox"===e.type||"radio"===e.type)if(!0===a)e.checked=!0;else if(!1===a)e.checked=!1;else{const k=B(e).ea();e.checked=k===a+""}else e.value=a});return this};B=(a,e)=>{const k=new h;if(a)if("function"===typeof a)v?a():m.push(a);
else if("string"===typeof a){a=a.trim();if(a.match(/^</))return B(B.W(a));f(k,a,e)}else if(a.nodeName)k.j(a);else{if(!(e=P.isArray(a))){e=a;const u=Object.prototype.toString.call(e);e="object"===typeof e&&/^\[object (HTMLCollection|NodeList|Object)\]$/.test(u)&&"number"===typeof e.length&&(0===e.length||"object"===typeof e[0]&&0<e[0].nodeType)}e||a instanceof h?k.j.apply(k,a):k.j(a)}return k};B.W=a=>{var e=document.implementation.createHTMLDocument(""),k=e.createDocumentFragment(),u=a.match(/^(<tbody|<thead|<tfoot)/i)?
"table":"body";u=a.match(/^<tr/i)?"tbody":u;u=a.match(/^<td/i)?"tr":u;if(a.match(/^<link/i)&&e.createStyleSheet){k=a.match("href=[\"'](.*)?[\"']")[1];u=a.match("rel=[\"'](.*)?[\"']");a=a.match("media=[\"'](.*)?[\"']");try{var n=e.createStyleSheet(k)}catch(I){n=e.createElement("link"),n.href=k}u&&(n.rel=u[1]);a&&(n.media=a[1]);return[n]}if(a.match(/^<script/i))return a=a.match("src=[\"'](.*)?[\"']"),e=e.createElement("script"),e.async=!0,a&&(e.src=a[1]),[e];e=e.createElement(u);e.innerHTML=a;for(n=
[];a=e.firstChild;)n.push(a),k.appendChild(a);return n};const f=(a,e,k)=>{e=(e||"").trim();k=(k="string"===typeof k?k.trim():k)||J;k="string"===typeof k?J.querySelectorAll(k):k;"length"in k?B(k).i(u=>{a.j.apply(a,u.querySelectorAll(e))}):a.j.apply(a,k.querySelectorAll(e))},l=a=>{if(a){if(11===a.getRootNode().nodeType)return a.getRootNode();if(9===a.nodeType)return a;if(a.ownerDocument)return a.ownerDocument}return J},p=a=>{v=!0;for(let e=0,k=m.length;e<k;e++)m[e](a);m=[]},r=J.readyState;"complete"===
r||"interactive"===r?p():t(C,"DOMContentLoaded",p)})();var da;(()=>{function h(){this.o={}}const v={};da=m=>m?v[m]=v[m]||new h(m):new h;h.prototype={B:function(m,t){m=this.o[m];for(let c in m)m[c](t);return this},P:function(m,t){t?delete this.o[m][t]:delete this.o[m];return this},R:function(m,t){const c=R.pa();this.o[m]=this.o[m]||{};this.o[m][c]=t;return c}}})();const H={};(()=>{function h(f){H.N().every(l=>l.name===f.voice?(t=l,!1):!0)}const v=C.speechSynthesis,m=da("AUDIO_EVENTS");var t=null,c=
null==v?void 0:v.getVoices();H.R=m.R.bind(m);H.P=m.P.bind(m);H.N=()=>c.length?c:(null==v?void 0:v.getVoices())||[];H.Ba=()=>"undefined"===typeof v?!1:!0;H.aa=()=>v.speaking;H.ba=(f,l)=>{const p=H.N(),r=new C.SpeechSynthesisUtterance;var a=f.split(/[_-]/),e;f=null==(e=a[0])?void 0:e.toLowerCase();var k;e=null==(k=a[1])?void 0:k.toUpperCase();a=ia[f]||{};const u=a[e],n=Object.keys(a);k=null;u?(k=u[0],t&&-1<u.indexOf(t)&&(k=t)):n.length&&(k=a[n[0]][0]);if(k)for(a=0;a<p.length;a++)if(p[a].voiceURI===
k){r.voice=p[a];break}f&&e&&(r.lang=`${f}-${e}`);r.text=l;r.onstart=()=>{m.B("SPEECH_START")};r.onend=()=>{m.B("SPEECH_END")};r.onerror=I=>{m.B("SPEECH_END");S(I,null)};return r};H.Ea=(f,l)=>{if(H.aa())return!1;f=H.ba(f,l);speechSynthesis.speak(f);return!0};A.O("USER_PREFERENCES_UPDATED",h);A.C("USER_PREFERENCES_GET_ALL",h)})();(()=>{let h,v;try{C.SpeechSynthesisUtterance&&(C.speechSynthesis.getVoices(),v=new SpeechSynthesisUtterance,v.voiceURI="native",v.volume=1,v.rate=.75,v.pitch=1,v.lang="en-US")}catch(c){S(c,
null)}let m={F:!0,data:{K:0,sa:(new Date).getFullYear(),va:{a:"Adjective",n:"Noun",r:"Adverb",s:"Adjective",v:"Verb"},qa:{adjective:"adjective",comparative:"comparative adjective",superlative:"superlative adjective"},ua:{singular:"noun",plural:"plural noun"},za:{"3pp":"3rd person present",g:"gerund or present participle",pp:"past participle",pt:"past tense",verb:"verb"},result:null,Pa:[],active:!1,M:"",q:""},methods:{wa:function(){h.K++;return h.K},xa:function(){h.K=0;return""},define:function(c){h.M=
c;A.C("DEFINE",{term:c,trigger:"page-action-form-click"},f=>{h.M=c;let l,p;(f=null==f?void 0:null==(l=f.data)?void 0:null==(p=l.data)?void 0:p.searchResults)?h.result=f[0]:h.results=[{source:"NOT_FOUND"}]});return!1},submit:function(c){c.preventDefault();c=B("#q").X();if(null==c||!c.trim().length)return!1;m.methods.define(c)},Oa:function(c,f,l){f++;return f===c.length||f===l},speak:function(){if(C.speechSynthesis&&!h.L&&v){const c=window.speechSynthesis,f=new SpeechSynthesisUtterance(h.result.title);
f.onend=()=>{h.L=!1};f.onerror=()=>{h.L=!1};f.pitch=1;f.rate=1;c.speak(f);h.L=!0}}},Z:function(){},m:function(c,f){let l,p,r,a,e;return'<div> <header> <form id="search-form" on:click.prevent.stop="methods.submit"> <input id="q" size="24" x-webkit-speech v-model="term"> <input type="submit" value="Define"> </form> \x3c!--div id="autocomplete"> <ul class="autocomplete" v-if="suggestions.length"> <li :index="$index" class="autocomplete-item" v-for="(suggestion, $index) in suggestions" v-bind:class="{\'autocomplete-item-focus\': suggestion._focus}" :title="suggestion.title"> <div v-html="suggestion.html"></div> </li> </ul> </div> <div id="press_enter">Press Enter to search.</div--\x3e </header> <article> '+
(c.result?`<div id="search-result">${f.xa()} <div id="title"> `+("NOT_FOUND"===c.result.source?`<div> <h3>No results found for: <i>${c.M}</i></h3> </div> `:"")+("dictionary"===c.result.source?`<div> <h1>${c.result.hyphenated||c.result.title}</h1> <div id="meta"> <a class="audio_pronunciation" href="javascript:void(0);" data-term="${c.result.title}" on:click.prevent.stop="methods.speak">audio</a> `+((null==(l=c.result)?0:null==(p=l.pronunciations)?0:p.pronun1)?`<span> <abbr title="North American English">NAmE.</abbr> / <span class="pronunciation">${c.result.pronunciations.pronun1}</span>/ </span> `:
"")+((null==(r=c.result)?0:null==(a=r.pronunciations)?0:a.pronun2)?`<span> &nbsp; | &nbsp; <abbr title="British English">BrE.</abbr>/ <span class="pronunciation">${c.result.pronunciations.pronun2}</span>/ <!--a class="audio_pronunciation" :href="'https://www.goodwordguide.com/audio/mp3/' + result.pronunciations.en_uk + '.mp3'" title="#" :data-term="result.title" v-on:click="speak">audio</a--> </span>`:"")+" </div> </div>":"")+("wikipedia"==c.result.source?`<div class="so_content" id="so_wiki"> <h2>${c.result.title}</h2> `+
(c.result.caption?`<div id="so_wiki_caption">${c.result.caption}</div>`:"")+`<p id="so_wiki_abstr"> <span id="so_wiki_abstr_text">${c.result["abstract"]}</span> `+(c.result["abstract"]?`<a target="_blank" class="so_link_ext" href="'https://en.wikipedia.org/wiki/' + ${c.result.link}">Wikipedia</a>`:"")+" </p> </div>":"")+" </div>"+("dictionary"===c.result.source?'<section id="meaning">'+(null==(e=c.result.order)?void 0:e.map((k,u)=>`<div> <h2>${c.result.title} <span class="word_count">${u+1}</span> <em>(${c.va[k]})</em></h2> `+
("a"===k?'<div class="meta"> '+Object.keys(c.result.adjective_forms).map(n=>`<span> <span>${c.qa[n]}</span>: <b>${c.result.adjective_forms[n]}</b>; </span>`).join("")+"</div>":"")+("n"===k?'<div class="meta">'+Object.keys(c.result.noun_forms).map(n=>`<span> <span>${c.ua[n]}</span>: <b>${c.result.noun_forms[n]}</b>; </span>`).join("")+" </div>":"")+("v"===k?' <div class="meta"> '+Object.keys(c.result.verb_forms).map(n=>`<span> <span>${c.za[n]}</span>: <b>${c.result.verb_forms[n]}</b>; </span>`).join("")+
" </div>":"")+" <ol>"+c.result.definitions[k].map(n=>`<li> <span class="definition_no"><span>${f.wa()}</span>.</span> <span>${n.definition}</span>`+(n.examples?"<span>:</span> <ul>"+n.examples.slice(0,2).map(I=>`<li>${I}</li> `).join("")+" </ul>":"<span>.</span></span>")+" </li>").join("")+" </ol> </div> ").join(""))+" </section>":"")+" </div>":"")+' <div id="lookup-status"></div> '+(c.result?"":"<div id=\"usage-tip\">Tip: Select text on any webpage, then click the 'D' button to view the definition of your selection.</div>")+
` </article> <span id="audio"></span> <footer>\u00a9<span>${c.sa}</span> Good Word Guide - <a id="options-link" href="options.html" target="_blank">Extension Options</a></footer> </div>`}},t=new ma(B("#body")[0],m);h=t.data;t.I();B(J).ka(()=>{});A.S("GET_SELECTION",c=>{(c=(c||"").trim())?(m.methods.define(c),B("#q").X(c)):B("#q").ha()});A.S("CLOSE_POPUP")})()})();
//# sourceMappingURL=page-action.js.map