"use strict";

const MESSAGE_TYPES = {
  addCustomCssByHost: 'add-custom-css-by-host',
  blockElement: 'block-element',
  blockElementInContent: 'block-element-in-content',
  countBlockedElementsRequest: 'count-blocked-elements-request',
  countBlockedElementsResponse: 'count-blocked-elements-response',
  extensionUrlOpened: 'extension-url-opened',
  getAppDataRequest: 'get-app-data-request',
  getAppDataResponse: 'get-app-data-response',
  getBlockingDataRequest: 'get-blocking-data-request',
  getBlockingDataResponse: 'get-blocking-data-response',
  getDataProcessingConsentRequest: 'get-data-processing-consent-request',
  getDataProcessingConsentResponse: 'get-data-processing-consent-response',
  getPageDataForContentRequest: 'get-page-data-for-content-request',
  getPageDataForContentResponse: 'get-page-data-for-content-response',
  getUserSettingsRequest: 'get-user-settings-request',
  getUserSettingsResponse: 'get-user-settings-response',
  openSettingsPage: 'open-settings-page',
  popupBlocked: 'popup-blocked',
  popupUserAction: 'popup-user-action',
  sendEmail: 'send-email',
  setDataProcessingConsent: 'set-data-processing-consent',
  stndzPopupAction: 'stndz-popup-action',
  stndzPopupInfo: 'stndz-popup-info',
  stndzPopupUpdate: 'stndz-popup-update',
  stndzShowPopupNotification: 'stndz-show-popup-notification',
  toggleSiteInListRequest: 'toggle-site-in-list-request',
  toggleSiteInListResponse: 'toggle-site-in-list-response',
  undoBlockedElementsRequest: 'undo-blocked-elements-request',
  undoBlockedElementsResponse: 'undo-blocked-elements-response',
  updatePageData: 'update-page-data',
  updateStatistics: 'update-statistics',
  updateUserSettingsRequest: 'update-user-settings-request',
  updateUserSettingsResponse: 'update-user-settings-response'
};